version: "3.7"
services:
  postgres:
    container_name: dealer-db
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ./.var/postgresql:/var/lib/postgresql/data
    ports:
      - "5435:5430"
  redis:
    container_name: dealer-redis
    image: redis:6-alpine
    volumes:
      - ./.var/redis:/data
    ports:
      - "6379:6379"
  app:
    container_name: dealer-app
    build: .
    command: |
      gunicorn --workers=2 --bind=0.0.0.0:8000 config.wsgi:application
    volumes:
      - .:/app
      - ./config/staticfiles
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres
      - celery
      - redis
      - celery-beat
      - flower
  nginx:
    image: nginx:1.17
    container_name: ngx
    ports:
      - "87:87"
    volumes:
      - ./config/staticfiles
      - ./nginx.conf
    depends_on:
      - app
  celery:
    container_name: dealer-celery
    build: .
    command: celery -A config worker
    volumes:
      - .:/app
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis
  celery-beat:
    container_name: dealer-celery-beat
    build: .
    command: celery -A config beat
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=8888
    ports:
      - 8888:8888
