name: Python application

on:
  push:
    branches: [ feature_celery, develop ]
  pull_request:
    branches: [ feature_celery, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
      env:
        SECRET_KEY: ${{ secrets.SecretKey }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install dependencies for testing
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 .
    - name: Test with pytest
      env:
        SECRET_KEY: ${{ secrets.SecretKey }}
        POSTGRES_DB: ${{ secrets.SecretKey }}
        POSTGRES_PASSWORD: ${{ secrets.SecretKey }}
        POSTGRES_USER: ${{ secrets.SecretKey }}
        POSTGRES_HOST: ${{ secrets.SecretKey }}
        POSTGRES_PORT: ${{ secrets.SecretKey }}
        REDIS_HOST: ${{ secrets.SecretKey }}
        REDIS_PORT: ${{ secrets.SecretKey }}
      run: pytest
    - name: Generate Report
      run: |
        pip install coverage
        coverage run -m pytest