name: Python application

on:
  push:
    branches: [ feature_celery, develop ]
  pull_request:
    branches: [ feature_celery, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        env:
          SECRET_KEY: ${{ secrets.SecretKey }}
          POSTGRES_DB: ${{ secrets.SecretKey }}
          POSTGRES_PASSWORD: ${{ secrets.SecretKey }}
          POSTGRES_USER: ${{ secrets.SecretKey }}
          POSTGRES_HOST: ${{ secrets.SecretKey }}
          POSTGRES_PORT: ${{ secrets.SecretKey }}
          REDIS_HOST: ${{ secrets.SecretKey }}
          REDIS_PORT: ${{ secrets.SecretKey }}
        run: |
          pip install pytest
          pytest
    
    
    

